# Generated by Django 6.0 on 2026-01-02 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('business_type', models.CharField(choices=[('self-employment', 'Self Employment'), ('uk-property', 'UK Property')], max_length=20)),
                ('trade_name', models.CharField(blank=True, max_length=200)),
                ('accounting_period_start', models.DateField()),
                ('accounting_period_end', models.DateField()),
                ('cash_or_accruals', models.CharField(choices=[('cash', 'Cash'), ('accruals', 'Accruals')], default='cash', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Businesses',
                'ordering': ['name'],
            },
        ),
    ]
